spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "257689830576-38aqp4upd6v6mgc7hmkaqakrjkf8kvus.apps.googleusercontent.com"
            client-secret: "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"
            scope: profile, email